import io
import json
import logging
import soundfile as sf
from pathlib import Path
from config import Config

logger = logging.getLogger("tts_service")


class KokoroTTSEngine:
    def __init__(self):
        self.kokoro = None
        self.voices = []

    def load(self):
        if self.kokoro is not None:
            return self.kokoro

        model_p = Path(Config.MODEL_PATH)
        voices_p = Path(Config.VOICES_PATH)
        model_p.parent.mkdir(parents=True, exist_ok=True)

        if not model_p.exists():
            import urllib.request
            logger.info("Kokoro model not found on disk. Auto-downloading kokoro-v0_19.onnx (325 MB)...")
            url = "https://github.com/thewh1teagle/kokoro-onnx/releases/download/model-files-v1.0/kokoro-v0_19.onnx"
            urllib.request.urlretrieve(url, str(model_p))
            logger.info("Kokoro ONNX model downloaded successfully.")

        if not voices_p.exists():
            import urllib.request
            logger.info("Kokoro voices not found on disk. Auto-downloading voices-v1.0.bin (28 MB)...")
            url = "https://github.com/thewh1teagle/kokoro-onnx/releases/download/model-files-v1.0/voices-v1.0.bin"
            urllib.request.urlretrieve(url, str(voices_p))
            logger.info("Kokoro voices downloaded successfully.")

        try:
            from kokoro_onnx import Kokoro
        except Exception as e:
            logger.error("Failed to import kokoro_onnx (%s). If on Linux, run: apt-get install -y espeak-ng", e)
            raise

        logger.info("Loading Kokoro ONNX model from %s...", Config.MODEL_PATH)
        self.kokoro = Kokoro(str(Config.MODEL_PATH), str(Config.VOICES_PATH))

        # Discover voices from loaded voices object
        try:
            if hasattr(self.kokoro.voices, "files"):
                self.voices = list(self.kokoro.voices.files)
            elif isinstance(self.kokoro.voices, dict):
                self.voices = list(self.kokoro.voices.keys())
            else:
                self.voices = [
                    "af_heart", "af_bella", "af_nicole", "af_sky",
                    "am_adam", "am_michael", "bf_emma", "bf_isabella",
                    "bm_george", "bm_lewis"
                ]
        except Exception:
            self.voices = ["af_heart", "af_bella", "am_adam", "bf_emma"]

        logger.info("Kokoro model loaded ready! Available voices: %d", len(self.voices))
        return self.kokoro

    def synthesize(self, text: str, voice: str = None, speed: float = 1.0) -> bytes:
        """Synthesizes text into WAV audio bytes."""
        engine = self.load()
        selected_voice = voice or Config.DEFAULT_VOICE

        samples, sample_rate = engine.create(
            text=text,
            voice=selected_voice,
            speed=speed,
            lang="en-us"
        )

        buffer = io.BytesIO()
        sf.write(buffer, samples, sample_rate, format="WAV")
        buffer.seek(0)
        return buffer.read()


tts_engine = KokoroTTSEngine()


# ==============================================================================
# OPTIONAL SAFETENSORS TTS ENGINE (PyTorch / Kokoro Native Safetensors)
# To use PyTorch Safetensors TTS models (e.g., hexgrad/Kokoro-82M safetensors):
# 1. Install dependencies:
#    pip install torch torchaudio soundfile kokoro
# 2. Point KOKORO_MODEL_PATH in .env to the repo or safetensors directory.
# 3. Swap the active engine instance:
#    # tts_engine = KokoroTTSEngine()
#    tts_engine = PyTorchKokoroSafetensorsEngine()
# ==============================================================================
# import torch
# from kokoro import KPipeline
#
# class PyTorchKokoroSafetensorsEngine:
#     """Direct PyTorch Safetensors loader for Kokoro / PyTorch TTS."""
#     def __init__(self, lang_code: str = "a"):
#         self.lang_code = lang_code
#         self.pipeline = None
#         self.voices = [
#             "af_heart", "af_bella", "af_nicole", "af_sky",
#             "am_adam", "am_michael", "bf_emma", "bf_isabella",
#             "bm_george", "bm_lewis"
#         ]
#
#     def load(self):
#         if self.pipeline is not None:
#             return self.pipeline
#         logger.info("Initializing PyTorch Safetensors Kokoro pipeline (lang=%s)...", self.lang_code)
#         self.pipeline = KPipeline(lang_code=self.lang_code)
#         return self.pipeline
#
#     def synthesize(self, text: str, voice: str = None, speed: float = 1.0) -> bytes:
#         pipeline = self.load()
#         selected_voice = voice or Config.DEFAULT_VOICE
#
#         generator = pipeline(text, voice=selected_voice, speed=speed, split_pattern=r'\n+')
#         audio_pieces = []
#         sample_rate = 24000
#
#         for _, _, audio in generator:
#             audio_pieces.append(audio)
#
#         if not audio_pieces:
#             raise RuntimeError("No audio was generated by PyTorch Kokoro engine.")
#
#         import numpy as np
#         combined_audio = np.concatenate(audio_pieces)
#
#         buffer = io.BytesIO()
#         sf.write(buffer, combined_audio, sample_rate, format="WAV")
#         buffer.seek(0)
#         return buffer.read()
